### ISSUE TITLE
Helm deployment fails with containerSecurityContext

### ISSUE THREAD

**Issue by lkindere** [apache/polaris#1071]
### Describe the bug

Hello,

When deploying with a containerSecurityContext and runAsUser polaris pod fails to start with the following error:

`Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
/usr/local/s2i/run: line 21: /opt/jboss/container/java/run/run-java.sh: Permission denied
/usr/local/s2i/run: line 21: exec: /opt/jboss/container/java/run/run-java.sh: cannot execute: Permission denied`

### To Reproduce

1. ./gradlew clean :polaris-quarkus-server:assemble :polaris-quarkus-admin:assemble \
    -Dquarkus.container-image.build=true \   
    -PeclipseLinkDeps=org.postgresql:postgresql:42.7.4 \
    --no-build-cache

2. Helm deploy with the built image using the following values.yaml:

```
storage:
  secret:
    name: polaris-storage
    awsAccessKeyId: access-key
    awsSecretAccessKey: secret-key

serviceAccount:
  create: false

image:
  repository: polaris
  pullPolicy: IfNotPresent
  tag: "1.0.0-incubating-SNAPSHOT"

imagePullSecrets:
  - token

containerSecurityContext:
   allowPrivilegeEscalation: false
   runAsNonRoot: true
   runAsUser: 1000
   capabilities:
     drop: [ "ALL" ]
   seccompProfile:
     type: RuntimeDefault

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
   memory: 128Mi
```

### Actual Behavior

Polaris pod fails to start with error

```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
/usr/local/s2i/run: line 21: /opt/jboss/container/java/run/run-java.sh: Permission denied
/usr/local/s2i/run: line 21: exec: /opt/jboss/container/java/run/run-java.sh: cannot execute: Permission denied
```

### Expected Behavior

Polaris pods started

### Additional context

I have additionally tried to set runAsUser: 10000 as that seems to be referenced in the docker image for the server but that fails even before there are any logs:

```
terminated
Reason:Reason: StartError - exit code: 128
Started at: 1970-01-01T01:00:00+01:00
Finished at: 2025-02-26T12:09:43+01:00
```

### System information

linux/amd64 image

**Comment by adutra** [comment]
Hi @lkindere thanks for reporting this! 

I see that you are using a custom Polaris image. Have you checked that the security context you specified matches the image contents? Especially the UID/GID settings should reflect what the image expects.

**Comment by adutra** [comment]
If you are using Polaris default Dockerfile, then the UID should be 10000:

https://github.com/apache/polaris/blob/main/quarkus/server/src/main/docker/Dockerfile.jvm

**Comment by lkindere** [comment]
@adutra it seems to work on my local machine, it is probably some kind of restriction on the workspace and an actual bug. Sorry for the confusion.

**Comment by lkindere** [comment]
Actually it looks like the problem is with 

```
containerSecurityContext:
   capabilities:
     drop: [ "ALL" ]
```

For example this succeeds:

```
image:
  pullPolicy: Never

storage:
  secret:
    name: polaris-storage
    awsAccessKeyId: access-key
    awsSecretAccessKey: secret-key

containerSecurityContext:
   allowPrivilegeEscalation: false
   runAsNonRoot: true
   runAsUser: 10000
  #  capabilities:
  #    drop: [ "ALL" ]
   seccompProfile:
     type: RuntimeDefault

```

While this fails:

```
image:
  pullPolicy: Never

storage:
  secret:
    name: polaris-storage
    awsAccessKeyId: access-key
    awsSecretAccessKey: secret-key

containerSecurityContext:
   allowPrivilegeEscalation: false
   runAsNonRoot: true
   runAsUser: 10000
   capabilities:
     drop: [ "ALL" ]
   seccompProfile:
     type: RuntimeDefault

```

Is there any way to deploy it with the capabilities dropped, as this is an enforcement we have on the Kubernetes cluster?
