### ISSUE TITLE
Wrong project and license in `pyproject.toml`

### ISSUE THREAD

**Issue by snazy** [apache/polaris#757]
### Describe the bug

The contents of `regtests/client/python/pyproject.toml` contains

```toml
[tool.poetry]
name = "polaris"
version = "1.0.0"
description = "Polaris Management Service"
authors = ["OpenAPI Generator Community <team@openapitools.org>"]
license = "NoLicense"
readme = "README.md"
repository = "https://github.com/GIT_USER_ID/GIT_REPO_ID"
keywords = ["OpenAPI", "OpenAPI-Generator", "Polaris Management Service"]
include = ["polaris.management/py.typed"]
```

which has wrong values for authors, license, repository, keywords.
