### ISSUE TITLE
Admin tool: add support for reading directory of credential files

### ISSUE THREAD

**Issue by adutra** [apache/polaris#878]
### Is your feature request related to a problem? Please describe.

The bootstrap command currently takes its input from command line arguments.

But the best for Kubernetes would be to store the bootstrap credentials in a secret, that could look like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: polaris-bootstrap-creds
data:
  realm1: "client1:secret1"
  realm2: "client2:secret2"
```

Then the secret could be mounted and each entry would become a file named `realm1`, `realm2` etc. with contents `client1:secret1`, `client2:secret2` etc.

It would be awesome if the bootstrap command could parse the directory and create the credentials from the files.

### Describe the solution you'd like

No more annoying messages.
