### ISSUE TITLE
API docs on polaris.apache.org are broken

### ISSUE THREAD

**Issue by collado-mike** [apache/polaris#941]
### Describe the bug

API docs generated from the specs are broken on the apache site: https://polaris.apache.org/in-dev/unreleased/rest-catalog-open-api/ . Currently, they don't load at all, but previously when they did load, the links to various APIs didn't work at all.

### To Reproduce

Go to https://polaris.apache.org/in-dev/unreleased/rest-catalog-open-api/

**Comment by HonahX** [comment]
Thanks @collado-mike ! I also discovered the same. Initially I thought it was due to my recent change: https://github.com/apache/polaris/pull/935, but the site sill breaks even after it is reverted: #942 

The current error is:

```
Refused to load the script 'https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://analytics.apache.org/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by singhpk234** [comment]
Adding 

```
<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js">
```

fixes this, tested locally, got this from the following SO thread, 
https://stackoverflow.com/a/37308542

Happy to create a PR if no one else is working on it ! 

Side note : Not sure how it worked before

**Comment by HonahX** [comment]
@singhpk234 Thanks for the solution! Just curious, how do you reproduce the issue locally. My local build works fine even without the added meta

**Comment by singhpk234** [comment]
@HonahX  thank you for your question ! 

as you will see the default CSP policy which is getting applied when rendering https://polaris.apache.org/in-dev/unreleased/rest-catalog-open-api/

is 

```
"script-src 'self' 'unsafe-inline' 'unsafe-eval' https://analytics.apache.org/"
```

which our current script violate (Note this doesn't get applied to developement env), to replicate this 
please go to hugo.yaml and add this to the end before rendering your websire  

```
server:
  headers:
    for: /**
    values:
      Content-Security-Policy: "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://analytics.apache.org/"
```

To mitigate this add this policy 

```
server:
  headers:
    for: /**
    values:
      Content-Security-Policy: >2
            script-src 'self' https://cdn.jsdelivr.net 'unsafe-inline' 'unsafe-eval' https://analytics.apache.org/ https://cdn.jsdelivr.net
```

P.S Not an expert in this area :P, please take this with a grain of salt !
